### ISSUE TITLE
Getting started example fails at pulling data from s3://dvc-storage/

### ISSUE THREAD

**Issue by robogeek** [iterative/example-get-started-dev#3]
Following the example at https://github.com/iterative/example-get-started, it fails at this point:

```
$ dvc remote list
s3	s3://dvc-storage

$ dvc pull -r s3
Preparing to download data from 's3://dvc-storage'
Preparing to collect status from s3://dvc-storage
[#########                     ] 30% Collecting information
Error: failed to pull data from the cloud - Unable to locate credentials

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

Since this is a "Getting Started" example that is supposed to work, then this step should be downloading prepared data from a remote cache that is somewhere.

**Comment by shcheklein** [comment]
@robogeek hmm, interesting.

Yes, this data exists on S3. There is something wrong with our S3 connector. Was DVC installed with boto3 support (`pip install dvc[s3]`)? Can you do a `pip list` or `pip freeze`, please?

**Comment by robogeek** [comment]
I did the pip install -r requirements.txt

**Comment by efiop** [comment]
In order to access even public s3 bucket, you need to have at least some aws creds. We could use http read-only remote instead, same as we do in dvc repo itself: https://github.com/iterative/dvc/blob/master/.dvc/config . That way it works even without boto3 installed.

**Comment by robogeek** [comment]
Yes that's my point, is that there should be zero configuration requirements to run the example.

**Comment by shcheklein** [comment]
All good points. I thought that `boto3` does not require initial configuration if you access publicly available  bucket. I'll change it to HTTP remote by default!

**Comment by shcheklein** [comment]
@robogeek David, I've updated it to use HTTP remote instead. Please, give it a try again, should be working now.

**Comment by shcheklein** [comment]
Fixed by https://github.com/iterative/example-get-started-dev/commit/9bc6bf852cf47d0409b75f488c2bc5a2bfc683e2
